project:
  name: my-image-classifier

paths:
  data_dir: data

  raw:
    images: data/raw/images
    metadata: data/raw/metadata

    ground_truth_csv: data/raw/metadata/ISIC_2024_Training_GroundTruth.csv
    supplement_csv: data/raw/metadata/ISIC_2024_Training_Supplement.csv
    metadata_csv: data/raw/metadata/metadata.csv

  interim:
    images: data/interim/images
    metadata: data/interim/metadata

  processed:
    images: data/processed/images
    metadata: data/processed/metadata

  external:
    images: data/external/images
    metadata: data/external/metadata

  models: data/models
