from __future__ import annotations

import argparse
import json
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Iterator

import numpy as np
import pandas as pd
import pyarrow.parquet as pq
import torch
import torch.nn as nn
import torchvision
from PIL import Image, UnidentifiedImageError
from torchvision import transforms
from torchvision.models import (
    ConvNeXt_Tiny_Weights,
    DenseNet121_Weights,
    EfficientNet_B0_Weights,
    ResNet50_Weights,
    convnext_tiny,
    densenet121,
    efficientnet_b0,
    resnet50,
)
from tqdm.auto import tqdm

from skin_lesion_ai.utils.data_utils import (
    load_yaml_config,
    path,
)

"""
Generate image embeddings from the preprocessed 136x136 lesion images.

The script reads the latest image preprocessing manifest generated by
preprocess_images.py, decodes the stored JPEG bytes, applies ImageNet
normalization without changing the project-selected image resolution, and
extracts one fixed-length embedding per lesion using a frozen pretrained CNN.

Supported feature extractors:
    - efficientnet_b0 -> 1280 features
    - resnet50        -> 2048 features
    - densenet121     -> 1024 features
    - convnext_tiny   -> 768 features

No SLICE-3D labels are used during embedding generation. The pretrained model
is kept in evaluation mode and all parameters are frozen. Therefore, the same
embedding files can later be reused for H1, H2, train/validation/test splits,
and different XGBoost experiments.

Outputs are written as timestamped Parquet shards to data/processed/images,
using the naming pattern:

    image_embeddings_<model>_<image_size>_<timestamp>_shard_<n>.parquet

A JSON manifest is also written with the model, weights, normalization,
source image manifest, embedding dimension and generated files.
"""

CONFIG_PATH = "configs/data_config.yaml"
INPUT_BASENAME = "raw_images_preprocessed"
OUTPUT_BASENAME = "image_embeddings"

DEFAULT_IMAGE_SIZE = 136
DEFAULT_BATCH_SIZE = 64
DEFAULT_IO_BATCH_SIZE = 2048
DEFAULT_OUTPUT_SHARD_ROWS = 20_000

SUPPORTED_MODELS = (
    "efficientnet_b0",
    "resnet50",
    "densenet121",
    "convnext_tiny",
)

# The pretrained TorchVision models used here are ImageNet classifiers.
# Images keep the project-selected 136x136 spatial resolution; only the
# ImageNet channel normalization is applied before feature extraction.
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)


# ---------------------------------------------------------------------
# Paths and manifests
# ---------------------------------------------------------------------


def get_image_directories(
    config_path: str | Path = CONFIG_PATH,
) -> tuple[Path, Path]:
    """Return interim image input directory and processed image output directory."""

    config = load_yaml_config(path(config_path))

    input_dir = path(config["paths"]["interim"]["images"])
    output_dir = path(config["paths"]["processed"]["images"])

    if not input_dir.exists():
        raise FileNotFoundError(f"Interim image directory not found: {input_dir}")

    output_dir.mkdir(parents=True, exist_ok=True)

    return input_dir, output_dir


def find_latest_image_manifest(
    input_dir: Path,
    image_size: int,
) -> Path:
    """Find the latest preprocessing manifest for the selected image size."""

    pattern = f"{INPUT_BASENAME}_{image_size}_*_manifest.json"
    manifests = sorted(input_dir.glob(pattern))

    if not manifests:
        raise FileNotFoundError(
            f"No image preprocessing manifest found for {image_size}x{image_size} "
            f"in {input_dir}. Expected pattern: {pattern}"
        )

    return manifests[-1]


def load_image_manifest(manifest_path: Path) -> dict:
    """Load and minimally validate an image preprocessing manifest."""

    with manifest_path.open("r", encoding="utf-8") as file:
        manifest = json.load(file)

    required_keys = {"image_size", "n_rows", "files"}
    missing_keys = required_keys.difference(manifest)

    if missing_keys:
        raise ValueError(
            f"Input manifest is missing required keys: {sorted(missing_keys)}"
        )

    if not manifest["files"]:
        raise ValueError("Input manifest does not contain any Parquet files.")

    return manifest


def resolve_input_files(
    manifest: dict,
    input_dir: Path,
) -> list[Path]:
    """Resolve Parquet paths stored in the preprocessing manifest."""

    resolved_files: list[Path] = []

    for raw_file in manifest["files"]:
        candidate = Path(raw_file)

        if candidate.exists():
            resolved_files.append(candidate)
            continue

        fallback = input_dir / candidate.name

        if fallback.exists():
            resolved_files.append(fallback)
            continue

        raise FileNotFoundError(
            f"Parquet file listed in manifest was not found: {raw_file}"
        )

    return resolved_files


# ---------------------------------------------------------------------
# Device and model
# ---------------------------------------------------------------------


def select_device(requested_device: str) -> torch.device:
    """Select CUDA, Apple MPS or CPU."""

    if requested_device != "auto":
        device = torch.device(requested_device)

        if device.type == "cuda" and not torch.cuda.is_available():
            raise RuntimeError("CUDA was requested but is not available.")

        if device.type == "mps" and not torch.backends.mps.is_available():
            raise RuntimeError("MPS was requested but is not available.")

        return device

    if torch.cuda.is_available():
        return torch.device("cuda")

    if torch.backends.mps.is_available():
        return torch.device("mps")

    return torch.device("cpu")


def build_feature_extractor(
    model_name: str,
    device: torch.device,
) -> tuple[nn.Module, int, str]:
    """Load a pretrained TorchVision model and remove its final classifier."""

    if model_name == "efficientnet_b0":
        weights = EfficientNet_B0_Weights.DEFAULT
        model = efficientnet_b0(weights=weights)
        embedding_dim = model.classifier[-1].in_features
        model.classifier[-1] = nn.Identity()

    elif model_name == "resnet50":
        weights = ResNet50_Weights.DEFAULT
        model = resnet50(weights=weights)
        embedding_dim = model.fc.in_features
        model.fc = nn.Identity()

    elif model_name == "densenet121":
        weights = DenseNet121_Weights.DEFAULT
        model = densenet121(weights=weights)
        embedding_dim = model.classifier.in_features
        model.classifier = nn.Identity()

    elif model_name == "convnext_tiny":
        weights = ConvNeXt_Tiny_Weights.DEFAULT
        model = convnext_tiny(weights=weights)
        embedding_dim = model.classifier[-1].in_features
        model.classifier[-1] = nn.Identity()

    else:
        raise ValueError(
            f"Unsupported model '{model_name}'. Choose one of: {SUPPORTED_MODELS}"
        )

    model.requires_grad_(False)
    model.eval()
    model.to(device)

    return model, int(embedding_dim), str(weights)


def build_image_transform() -> transforms.Compose:
    """Create the deterministic transform used before embedding extraction."""

    return transforms.Compose(
        [
            transforms.ToTensor(),
            transforms.Normalize(
                mean=IMAGENET_MEAN,
                std=IMAGENET_STD,
            ),
        ]
    )


# ---------------------------------------------------------------------
# Input streaming and image decoding
# ---------------------------------------------------------------------


def iter_parquet_batches(
    input_files: list[Path],
    io_batch_size: int,
) -> Iterator[pd.DataFrame]:
    """Stream only the columns required for embedding extraction."""

    required_columns = ["lesion_id", "patient_id", "image"]

    for input_file in input_files:
        parquet_file = pq.ParquetFile(input_file)
        available_columns = set(parquet_file.schema.names)
        missing_columns = set(required_columns).difference(available_columns)

        if missing_columns:
            raise ValueError(
                f"{input_file.name} is missing required columns: "
                f"{sorted(missing_columns)}"
            )

        for record_batch in parquet_file.iter_batches(
            batch_size=io_batch_size,
            columns=required_columns,
        ):
            yield record_batch.to_pandas()


def decode_image_bytes(
    image_bytes: bytes,
    image_size: int,
    transform: transforms.Compose,
) -> torch.Tensor:
    """Decode one JPEG byte sequence and convert it to a normalized tensor."""

    try:
        with Image.open(BytesIO(image_bytes)) as image:
            image = image.convert("RGB")

            if image.size != (image_size, image_size):
                raise ValueError(
                    f"Expected {image_size}x{image_size}, got "
                    f"{image.size[0]}x{image.size[1]}."
                )

            return transform(image)

    except UnidentifiedImageError as exc:
        raise UnidentifiedImageError(
            "Could not decode one of the JPEG byte sequences."
        ) from exc


def iter_inference_batches(
    dataframe: pd.DataFrame,
    batch_size: int,
    image_size: int,
    transform: transforms.Compose,
) -> Iterator[tuple[list[str], list[str], torch.Tensor]]:
    """Convert one streamed Parquet batch into smaller model inference batches."""

    for start in range(0, len(dataframe), batch_size):
        batch_df = dataframe.iloc[start : start + batch_size]

        tensors = [
            decode_image_bytes(
                image_bytes=image_bytes,
                image_size=image_size,
                transform=transform,
            )
            for image_bytes in batch_df["image"]
        ]

        image_tensor = torch.stack(tensors, dim=0)

        yield (
            batch_df["lesion_id"].astype(str).tolist(),
            batch_df["patient_id"].astype(str).tolist(),
            image_tensor,
        )


# ---------------------------------------------------------------------
# Embedding extraction and output
# ---------------------------------------------------------------------


def extract_embeddings(
    model: nn.Module,
    images: torch.Tensor,
    device: torch.device,
) -> np.ndarray:
    """Run one inference batch and return float32 embeddings on CPU."""

    images = images.to(device, non_blocking=device.type == "cuda")

    with torch.inference_mode():
        embeddings = model(images)

    if embeddings.ndim > 2:
        embeddings = torch.flatten(embeddings, start_dim=1)

    return embeddings.detach().to("cpu", dtype=torch.float32).numpy()


def build_embedding_dataframe(
    lesion_ids: list[str],
    patient_ids: list[str],
    embeddings: np.ndarray,
) -> pd.DataFrame:
    """Create a tabular dataframe with one column per embedding feature."""

    feature_columns = [f"feature_{idx:04d}" for idx in range(embeddings.shape[1])]

    embedding_df = pd.DataFrame(
        embeddings,
        columns=feature_columns,
        dtype=np.float32,
    )

    embedding_df.insert(0, "patient_id", patient_ids)
    embedding_df.insert(0, "lesion_id", lesion_ids)

    return embedding_df


def save_embedding_shard(
    lesion_ids: list[str],
    patient_ids: list[str],
    embedding_chunks: list[np.ndarray],
    output_dir: Path,
    model_name: str,
    image_size: int,
    timestamp: str,
    shard_idx: int,
) -> Path:
    """Concatenate buffered embeddings and save one Parquet shard."""

    embeddings = np.concatenate(embedding_chunks, axis=0)

    embedding_df = build_embedding_dataframe(
        lesion_ids=lesion_ids,
        patient_ids=patient_ids,
        embeddings=embeddings,
    )

    filename = (
        f"{OUTPUT_BASENAME}_{model_name}_{image_size}_{timestamp}"
        f"_shard_{shard_idx:03d}.parquet"
    )
    output_path = output_dir / filename

    embedding_df.to_parquet(output_path, index=False)

    return output_path


def generate_embeddings(
    input_files: list[Path],
    output_dir: Path,
    model_name: str,
    image_size: int,
    batch_size: int,
    io_batch_size: int,
    output_shard_rows: int,
    device: torch.device,
    expected_rows: int,
    timestamp: str,
    limit: int | None = None,
) -> tuple[list[Path], int, int, str]:
    """Generate and save embeddings for all selected images."""

    model, embedding_dim, weights_name = build_feature_extractor(
        model_name=model_name,
        device=device,
    )
    transform = build_image_transform()

    output_paths: list[Path] = []

    buffered_lesion_ids: list[str] = []
    buffered_patient_ids: list[str] = []
    buffered_embeddings: list[np.ndarray] = []
    buffered_rows = 0

    processed_rows = 0
    shard_idx = 0
    target_rows = expected_rows if limit is None else min(limit, expected_rows)

    progress = tqdm(
        total=target_rows,
        desc=f"Extracting {model_name} embeddings",
        unit="image",
    )

    for parquet_batch in iter_parquet_batches(
        input_files=input_files,
        io_batch_size=io_batch_size,
    ):
        if processed_rows >= target_rows:
            break

        remaining_rows = target_rows - processed_rows

        if len(parquet_batch) > remaining_rows:
            parquet_batch = parquet_batch.iloc[:remaining_rows].copy()

        for lesion_ids, patient_ids, images in iter_inference_batches(
            dataframe=parquet_batch,
            batch_size=batch_size,
            image_size=image_size,
            transform=transform,
        ):
            embeddings = extract_embeddings(
                model=model,
                images=images,
                device=device,
            )

            if embeddings.shape[1] != embedding_dim:
                raise RuntimeError(
                    f"Unexpected embedding dimension for {model_name}: "
                    f"expected {embedding_dim}, got {embeddings.shape[1]}."
                )

            buffered_lesion_ids.extend(lesion_ids)
            buffered_patient_ids.extend(patient_ids)
            buffered_embeddings.append(embeddings)

            current_batch_rows = len(lesion_ids)
            buffered_rows += current_batch_rows
            processed_rows += current_batch_rows
            progress.update(current_batch_rows)

            if buffered_rows >= output_shard_rows:
                # Keep shard boundaries simple: the current inference batch is
                # included completely, so a shard may exceed the target by less
                # than one inference batch.
                output_path = save_embedding_shard(
                    lesion_ids=buffered_lesion_ids,
                    patient_ids=buffered_patient_ids,
                    embedding_chunks=buffered_embeddings,
                    output_dir=output_dir,
                    model_name=model_name,
                    image_size=image_size,
                    timestamp=timestamp,
                    shard_idx=shard_idx,
                )
                output_paths.append(output_path)

                buffered_lesion_ids = []
                buffered_patient_ids = []
                buffered_embeddings = []
                buffered_rows = 0
                shard_idx += 1

            if processed_rows >= target_rows:
                break

    progress.close()

    if buffered_rows > 0:
        output_path = save_embedding_shard(
            lesion_ids=buffered_lesion_ids,
            patient_ids=buffered_patient_ids,
            embedding_chunks=buffered_embeddings,
            output_dir=output_dir,
            model_name=model_name,
            image_size=image_size,
            timestamp=timestamp,
            shard_idx=shard_idx,
        )
        output_paths.append(output_path)

    if processed_rows != target_rows:
        raise RuntimeError(
            f"Expected to process {target_rows:,} rows, but generated "
            f"{processed_rows:,} embeddings."
        )

    return output_paths, processed_rows, embedding_dim, weights_name


def save_embedding_manifest(
    output_dir: Path,
    model_name: str,
    image_size: int,
    output_paths: list[Path],
    n_rows: int,
    embedding_dim: int,
    weights_name: str,
    source_manifest_path: Path,
    device: torch.device,
    batch_size: int,
    io_batch_size: int,
    output_shard_rows: int,
    timestamp: str,
) -> Path:
    """Save metadata describing one embedding-generation run."""

    manifest = {
        "created_at": timestamp,
        "model": model_name,
        "weights": weights_name,
        "embedding_dim": embedding_dim,
        "image_size": image_size,
        "input_normalization": {
            "mean": list(IMAGENET_MEAN),
            "std": list(IMAGENET_STD),
        },
        "source_manifest": str(source_manifest_path),
        "n_rows": n_rows,
        "n_files": len(output_paths),
        "files": [str(output_path) for output_path in output_paths],
        "device": str(device),
        "batch_size": batch_size,
        "io_batch_size": io_batch_size,
        "output_shard_rows": output_shard_rows,
        "torch_version": torch.__version__,
        "torchvision_version": torchvision.__version__,
    }

    manifest_path = output_dir / (
        f"{OUTPUT_BASENAME}_{model_name}_{image_size}_{timestamp}_manifest.json"
    )

    with manifest_path.open("w", encoding="utf-8") as file:
        json.dump(manifest, file, indent=2)

    return manifest_path


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description=(
            "Generate frozen pretrained CNN embeddings from preprocessed lesion images."
        )
    )

    parser.add_argument(
        "--model",
        type=str,
        required=True,
        choices=SUPPORTED_MODELS,
        help="Pretrained CNN used as feature extractor.",
    )

    parser.add_argument(
        "--image-size",
        type=int,
        default=DEFAULT_IMAGE_SIZE,
        help=f"Expected preprocessed image size. Default: {DEFAULT_IMAGE_SIZE}.",
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=f"Model inference batch size. Default: {DEFAULT_BATCH_SIZE}.",
    )

    parser.add_argument(
        "--io-batch-size",
        type=int,
        default=DEFAULT_IO_BATCH_SIZE,
        help=(
            "Rows read at once from the input Parquet files. "
            f"Default: {DEFAULT_IO_BATCH_SIZE}."
        ),
    )

    parser.add_argument(
        "--output-shard-rows",
        type=int,
        default=DEFAULT_OUTPUT_SHARD_ROWS,
        help=(
            "Approximate rows per output Parquet shard. "
            f"Default: {DEFAULT_OUTPUT_SHARD_ROWS}."
        ),
    )

    parser.add_argument(
        "--device",
        type=str,
        default="auto",
        choices=("auto", "cpu", "cuda", "mps"),
        help="Inference device. Default: auto (CUDA > MPS > CPU).",
    )

    parser.add_argument(
        "--input-manifest",
        type=str,
        default=None,
        help=(
            "Optional exact preprocessing manifest path. If omitted, the latest "
            "manifest matching the selected image size is used."
        ),
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional image limit for testing the pipeline.",
    )

    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    """Validate positive numeric CLI arguments."""

    for argument_name in (
        "image_size",
        "batch_size",
        "io_batch_size",
        "output_shard_rows",
    ):
        value = getattr(args, argument_name)

        if value <= 0:
            raise ValueError(f"{argument_name} must be greater than 0.")

    if args.limit is not None and args.limit <= 0:
        raise ValueError("limit must be greater than 0 when provided.")


def main() -> None:
    """Run the complete image embedding generation pipeline."""

    args = parse_args()
    validate_args(args)

    input_dir, output_dir = get_image_directories()

    if args.input_manifest is None:
        source_manifest_path = find_latest_image_manifest(
            input_dir=input_dir,
            image_size=args.image_size,
        )
    else:
        source_manifest_path = Path(args.input_manifest).expanduser().resolve()

        if not source_manifest_path.exists():
            raise FileNotFoundError(f"Input manifest not found: {source_manifest_path}")

    source_manifest = load_image_manifest(source_manifest_path)

    if int(source_manifest["image_size"]) != args.image_size:
        raise ValueError(
            f"Manifest image size ({source_manifest['image_size']}) does not "
            f"match --image-size ({args.image_size})."
        )

    input_files = resolve_input_files(
        manifest=source_manifest,
        input_dir=input_dir,
    )

    expected_rows = int(source_manifest["n_rows"])
    device = select_device(args.device)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    print(f"Model: {args.model}")
    print(f"Device: {device}")
    print(f"Image size: {args.image_size}x{args.image_size}")
    print(f"Source manifest: {source_manifest_path}")
    print(f"Input Parquet files: {len(input_files)}")
    print(f"Available rows: {expected_rows:,}")
    print(f"Inference batch size: {args.batch_size}")
    print(f"Output directory: {output_dir}")

    output_paths, n_rows, embedding_dim, weights_name = generate_embeddings(
        input_files=input_files,
        output_dir=output_dir,
        model_name=args.model,
        image_size=args.image_size,
        batch_size=args.batch_size,
        io_batch_size=args.io_batch_size,
        output_shard_rows=args.output_shard_rows,
        device=device,
        expected_rows=expected_rows,
        timestamp=timestamp,
        limit=args.limit,
    )

    manifest_path = save_embedding_manifest(
        output_dir=output_dir,
        model_name=args.model,
        image_size=args.image_size,
        output_paths=output_paths,
        n_rows=n_rows,
        embedding_dim=embedding_dim,
        weights_name=weights_name,
        source_manifest_path=source_manifest_path,
        device=device,
        batch_size=args.batch_size,
        io_batch_size=args.io_batch_size,
        output_shard_rows=args.output_shard_rows,
        timestamp=timestamp,
    )

    print("\nEmbedding generation completed.")
    print(f"Rows processed: {n_rows:,}")
    print(f"Embedding dimension: {embedding_dim:,}")
    print(f"Output shards: {len(output_paths)}")
    print(f"Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
