"""
Image decoding and transformation utilities for model training.

This module contains low-level functions to convert preprocessed image bytes
stored in Parquet files into NumPy arrays suitable for modelling.

The image Parquet files generated by `scripts/preprocess_images.py` store each
resized image as JPEG bytes. This is efficient for disk storage, but models
need decoded numerical arrays or tensors during training and evaluation.

Recommended usage
-----------------
For neural networks:
    Decode and normalize images on the fly inside a Dataset/DataLoader.
    This avoids loading the full training set as float32 arrays in memory.

For classical models:
    Use these functions to generate features in batches or on smaller subsets.
    Directly flattening full images can be very memory-expensive.

For validation and test sets:
    Use the same transformation parameters used during training
    (normalization mode, mean, std and channel order).
"""

from __future__ import annotations
from io import BytesIO
from typing import Literal, Sequence

import numpy as np
import pandas as pd
from PIL import Image, UnidentifiedImageError


NormalizationMode = Literal["none", "scale_0_1", "mean_std"]
OutputDType = Literal["uint8", "float32"]
ChannelOrder = Literal["channels_last", "channels_first"]


def decode_image_bytes(image_bytes: bytes) -> np.ndarray:
    """
    Decode JPEG image bytes into an RGB NumPy array.

    Parameters
    ----------
    image_bytes:
        JPEG bytes stored in the Parquet image column.

    Returns
    -------
    np.ndarray
        Image array with shape (height, width, 3), dtype uint8 and pixel
        values in the 0-255 range.
    """
    try:
        with Image.open(BytesIO(image_bytes)) as img:
            img = img.convert("RGB")
            return np.asarray(img, dtype=np.uint8)

    except UnidentifiedImageError as exc:
        raise UnidentifiedImageError("Could not decode image bytes.") from exc


def _prepare_channel_values(
    values: float | Sequence[float],
    name: str,
) -> np.ndarray:
    """
    Convert scalar or RGB channel values to broadcastable HWC format.
    """
    values_array = np.asarray(values, dtype=np.float32)

    if values_array.ndim == 0:
        values_array = np.repeat(values_array, 3)

    if values_array.shape != (3,):
        raise ValueError(f"{name} must be either a scalar or a sequence of 3 values.")

    return values_array.reshape(1, 1, 3)


def normalize_image_array(
    image: np.ndarray,
    normalization: NormalizationMode = "scale_0_1",
    mean: float | Sequence[float] | None = None,
    std: float | Sequence[float] | None = None,
) -> np.ndarray:
    """
    Normalize an image array.

    Parameters
    ----------
    image:
        Image array with shape (height, width, 3).

    normalization:
        Normalization strategy:
        - "none": keep pixel values unchanged, only cast to float32.
        - "scale_0_1": divide pixel values by 255.
        - "mean_std": divide by 255 and then apply (image - mean) / std.

    mean:
        Mean value used when normalization="mean_std". Can be a scalar or
        a sequence of three RGB values. Values are expected in the 0-1 scale.

    std:
        Standard deviation used when normalization="mean_std". Can be a scalar
        or a sequence of three RGB values. Values are expected in the 0-1 scale.

    Returns
    -------
    np.ndarray
        Normalized image array with dtype float32.
    """
    if image.ndim != 3 or image.shape[-1] != 3:
        raise ValueError(
            f"Expected image with shape (height, width, 3). Got shape {image.shape}."
        )

    if normalization not in {"none", "scale_0_1", "mean_std"}:
        raise ValueError(
            "normalization must be one of: 'none', 'scale_0_1', 'mean_std'."
        )

    image = image.astype(np.float32, copy=False)

    if normalization == "none":
        return image

    image = image / 255.0

    if normalization == "scale_0_1":
        return image

    if mean is None or std is None:
        raise ValueError("mean and std must be provided when normalization='mean_std'.")

    mean_array = _prepare_channel_values(mean, name="mean")
    std_array = _prepare_channel_values(std, name="std")

    if np.any(std_array == 0):
        raise ValueError("std values must be non-zero.")

    return (image - mean_array) / std_array


def transform_image_bytes(
    image_bytes: bytes,
    output_dtype: OutputDType = "float32",
    normalization: NormalizationMode = "scale_0_1",
    mean: float | Sequence[float] | None = None,
    std: float | Sequence[float] | None = None,
    channel_order: ChannelOrder = "channels_last",
) -> np.ndarray:
    """
    Decode and transform one image from JPEG bytes.

    Parameters
    ----------
    image_bytes:
        JPEG bytes stored in the Parquet image column.

    output_dtype:
        Output dtype:
        - "uint8": return raw decoded pixels in the 0-255 range.
        - "float32": return a float32 array, optionally normalized.

    normalization:
        Normalization strategy:
        - "none": no pixel scaling.
        - "scale_0_1": divide by 255.
        - "mean_std": divide by 255 and then apply (image - mean) / std.

    mean:
        RGB mean values used when normalization="mean_std".
        Expected in the 0-1 scale.

    std:
        RGB standard deviation values used when normalization="mean_std".
        Expected in the 0-1 scale.

    channel_order:
        Output channel order:
        - "channels_last": shape (height, width, channels).
        - "channels_first": shape (channels, height, width).

    Returns
    -------
    np.ndarray
        Transformed image array.
    """
    if output_dtype not in {"uint8", "float32"}:
        raise ValueError("output_dtype must be either 'uint8' or 'float32'.")

    if channel_order not in {"channels_last", "channels_first"}:
        raise ValueError(
            "channel_order must be either 'channels_last' or 'channels_first'."
        )

    image = decode_image_bytes(image_bytes)

    if output_dtype == "uint8":
        if normalization != "none":
            raise ValueError("normalization must be 'none' when output_dtype='uint8'.")

        transformed = image

    else:
        transformed = normalize_image_array(
            image=image,
            normalization=normalization,
            mean=mean,
            std=std,
        )

    if channel_order == "channels_first":
        transformed = np.transpose(transformed, (2, 0, 1))

    return transformed


def transform_image_batch(
    image_bytes_list: Sequence[bytes],
    output_dtype: OutputDType = "float32",
    normalization: NormalizationMode = "scale_0_1",
    mean: float | Sequence[float] | None = None,
    std: float | Sequence[float] | None = None,
    channel_order: ChannelOrder = "channels_last",
    flatten: bool = False,
) -> np.ndarray:
    """
    Transform a small batch of images from JPEG bytes.

    This function is useful for debugging, validation checks, small baselines
    or batch-wise feature generation. It should not be used to transform the
    full image dataset at once unless memory usage has been considered.

    Parameters
    ----------
    image_bytes_list:
        Sequence of JPEG byte objects.

    output_dtype:
        Output dtype passed to `transform_image_bytes`.

    normalization:
        Normalization strategy passed to `transform_image_bytes`.

    mean:
        RGB mean values used when normalization="mean_std".

    std:
        RGB standard deviation values used when normalization="mean_std".

    channel_order:
        Output channel order.

    flatten:
        If True, each image is flattened into a one-dimensional vector.
        This can be useful for simple classical ML baselines, but may create
        very high-dimensional feature matrices.

    Returns
    -------
    np.ndarray
        Batch array with shape:
        - (n_images, height, width, channels) if channels_last
        - (n_images, channels, height, width) if channels_first
        - (n_images, n_features) if flatten=True
    """
    transformed_images = [
        transform_image_bytes(
            image_bytes=image_bytes,
            output_dtype=output_dtype,
            normalization=normalization,
            mean=mean,
            std=std,
            channel_order=channel_order,
        )
        for image_bytes in image_bytes_list
    ]

    batch = np.stack(transformed_images, axis=0)

    if flatten:
        batch = batch.reshape(batch.shape[0], -1)

    return batch


def compute_image_mean_std_from_dataframe(
    df: pd.DataFrame,
    image_column: str = "image",
    max_images: int | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Compute RGB channel mean and standard deviation from image bytes.

    Mean and std are computed in the 0-1 pixel scale. In a standard modelling
    workflow, this function should be applied to the training set only. The
    resulting mean and std should then be reused to normalize training,
    validation and test images through `transform_image_bytes`.

    Parameters
    ----------
    df:
        DataFrame containing a column with JPEG image bytes.

    image_column:
        Name of the column containing JPEG bytes.

    max_images:
        Optional maximum number of images to use. Useful for fast estimates.

    Returns
    -------
    tuple[np.ndarray, np.ndarray]
        RGB mean and standard deviation arrays, both with shape (3,).
    """
    if image_column not in df.columns:
        raise KeyError(f"Column '{image_column}' not found in dataframe.")

    image_bytes_series = df[image_column]

    if max_images is not None:
        image_bytes_series = image_bytes_series.head(max_images)

    channel_sum = np.zeros(3, dtype=np.float64)
    channel_sum_sq = np.zeros(3, dtype=np.float64)
    n_pixels = 0

    for image_bytes in image_bytes_series:
        image = decode_image_bytes(image_bytes).astype(np.float32) / 255.0

        pixels = image.reshape(-1, 3)

        channel_sum += pixels.sum(axis=0)
        channel_sum_sq += np.square(pixels).sum(axis=0)
        n_pixels += pixels.shape[0]

    if n_pixels == 0:
        raise ValueError("No images available to compute mean and std.")

    mean = channel_sum / n_pixels
    variance = (channel_sum_sq / n_pixels) - np.square(mean)
    std = np.sqrt(np.maximum(variance, 0))

    return mean.astype(np.float32), std.astype(np.float32)
